# Generated by Django 5.2.16 on 2026-07-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='crop',
            new_name='crop_type',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='product_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
